import type {Metadata} from "next";
import {Montserrat, Open_Sans, Roboto} from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/providers";
import NavigationBar from "@/components/navigation-bar";

const montserrat = Montserrat({
    variable: "--font-family",
  subsets: ["latin"],
});

const roboto = Roboto({
    variable: "--font-family",
  subsets: ["latin"],
});

const openSans = Open_Sans({
    variable: "--font-family",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`${montserrat.variable} ${roboto.variable} ${openSans.variable} antialiased`}
      >
      <Providers>
          <NavigationBar/>
          {children}
      </Providers>
      </body>
    </html>
  );
}
